apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAllowedBindingsConstraintV3
metadata:
  name: deny_allusers
  annotations:
    description: Prevent public users from having access to resources via IAM
    bundles.validator.forsetisecurity.org/scorecard-v1: security
    bundles.validator.forsetisecurity.org/healthcare-baseline-v1: security
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - "organizations/**"
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: denylist
    role: "roles/*"
    members:
   # - "allUsers"
   # - "allAuthenticatedUsers"
   # Add Service accounts used by the CICD Pipeline
    - cloubuild-dev-sa@w-app-pipeline.iam.gserviceaccount.com
    - cloubuild-prod-sa@w-app-pipeline.iam.gserviceaccount.com
    - w-targetdev-0805@w-appdev-0805.iam.gserviceaccount.com
